// Auto-generated by generate-example-docs.mjs - do not edit
import React from 'react';
import ManimExample from '../ManimExample';

async function animate(scene: any) {
  const { Arrow, NumberPlane, Scene, Text, YELLOW, GREEN_C, RED_C, applyMatrix } =
    await import('manim-web');

  const plane = new NumberPlane();
  scene.add(plane);

  const arrow1 = new Arrow({ start: [-2, -1, 0], end: [2, 1, 0], color: YELLOW });
  const arrow2 = new Arrow({ start: [0, -2, 0], end: [0, 2, 0], color: GREEN_C });
  const arrow3 = new Arrow({ start: [-1, 1, 0], end: [1, -1, 0], color: RED_C });

  scene.add(arrow1, arrow2, arrow3);

  const label = new Text({ text: 'Before shear', fontSize: 24, color: '#ffffff' });
  label.moveTo([0, 3.2, 0]);
  scene.add(label);

  await scene.wait(1);

  // Shear matrix: x' = x + 0.5*y, y' = y
  const shearMatrix = [
    [1, 0.5, 0],
    [0, 1, 0],
    [0, 0, 1],
  ];

  // Apply the shear to the plane and arrows simultaneously
  await scene.play(
    applyMatrix(plane, shearMatrix, { duration: 2 }),
    applyMatrix(arrow1, shearMatrix, { duration: 2 }),
    applyMatrix(arrow2, shearMatrix, { duration: 2 }),
    applyMatrix(arrow3, shearMatrix, { duration: 2 }),
  );

  // Update label
  scene.remove(label);
  const label2 = new Text({
    text: 'After shear — tips reconstructed',
    fontSize: 24,
    color: '#ffffff',
  });
  label2.moveTo([0, 3.2, 0]);
  scene.add(label2);

  await scene.wait(2);
}

export default function ApplyMatrixArrowsExample() {
  return <ManimExample animationFn={animate} />;
}
