// Auto-generated by generate-example-docs.mjs - do not edit
import React from 'react';
import ManimExample from '../ManimExample';

async function animate(scene: any) {
  const { Sphere, Cube, Dot3D, ThreeDAxes, makeDraggable, BLUE, GREEN, YELLOW } =
    await import('manim-web');

  const axes = new ThreeDAxes({
    xRange: [-4, 4, 1],
    yRange: [-4, 4, 1],
    zRange: [-3, 3, 1],
    axisColor: '#444444',
    tipLength: 0.2,
    tipRadius: 0.08,
    shaftRadius: 0.006,
  });

  const sphere = new Sphere({ radius: 0.4, color: BLUE, opacity: 0.8 });
  sphere.moveTo([-2, 0, 0]);

  const cube = new Cube({ sideLength: 0.6, color: GREEN, opacity: 0.8 });
  cube.moveTo([2, 0, 0]);

  const dot = new Dot3D({ color: YELLOW, radius: 0.2 });
  dot.moveTo([0, 2, 0]);

  scene.add(axes, sphere, cube, dot);

  // Make 3D objects draggable — they move on a camera-facing plane
  makeDraggable(sphere, scene);
  makeDraggable(cube, scene);
  makeDraggable(dot, scene);

  await scene.wait(15);
}

function createScene(container: HTMLElement, manim: any) {
  return new manim.ThreeDScene(container, {
    width: 800,
    height: 450,
    backgroundColor: '#000000',
    phi: 70 * (Math.PI / 180),
    theta: -45 * (Math.PI / 180),
    distance: 18,
    fov: 30,
  });
}

export default function DraggableObjects3DExample() {
  return <ManimExample animationFn={animate} createScene={createScene} />;
}
