// Auto-generated by generate-example-docs.mjs - do not edit
import React from 'react';
import ManimExample from '../ManimExample';

async function animate(scene: any) {
  const { Circle, Square, Dot, Line, Text, makeDraggable, BLUE, GREEN, RED, YELLOW, WHITE } =
    await import('manim-web');

  const circle = new Circle({ radius: 0.5, color: BLUE, fillOpacity: 0.8 });
  circle.moveTo([-2, 1, 0]);

  const square = new Square({ sideLength: 0.8, color: GREEN, fillOpacity: 0.8 });
  square.moveTo([2, 1, 0]);

  const dot = new Dot({ color: YELLOW, radius: 0.15 });
  dot.moveTo([0, -1, 0]);

  const line = new Line({ start: circle.getCenter(), end: dot.getCenter() }).setColor(RED);
  line.addUpdater(() => line.become(new Line({ start: circle.getCenter(), end: dot.getCenter() })));

  const label = new Text({ text: 'Drag the shapes!', fontSize: 24, color: WHITE });
  label.moveTo([0, 2.5, 0]);

  scene.add(circle, square, dot, line, label);

  makeDraggable(circle, scene);
  makeDraggable(dot, scene);
  makeDraggable(square, scene, { constrainY: [1, 1], snapToGrid: 0.5 });

  await scene.wait(15);
}

export default function DraggableObjectsExample() {
  return <ManimExample animationFn={animate} />;
}
