// Auto-generated by generate-example-docs.mjs - do not edit
import React from 'react';
import ManimExample from '../ManimExample';

async function animate(scene: any) {
  const { Scene, Circle, Square, Create, Transform, FadeOut, BLACK, BLUE, GREEN } =
    await import('manim-web');

  const square = new Square({ sideLength: 2.5, color: BLUE, fillOpacity: 0.5 });
  const circle = new Circle({ radius: 1.25, color: GREEN, fillOpacity: 0.5 });

  await scene.play(new Create(square));
  await scene.play(new Transform(square, circle));
  await scene.play(new FadeOut(square));

  // Export as GIF: scene.export('animation.gif', { fps: 15, quality: 10 })
  // Export as WebM: scene.export('animation.webm', { fps: 30 })
  // Export as MP4: scene.export('animation.mp4')
  // Export as MOV: scene.export('animation.mov')
}

export default function ExportAnimationExample() {
  return <ManimExample animationFn={animate} />;
}
