// Auto-generated by generate-example-docs.mjs - do not edit
import React from 'react';
import ManimExample from '../ManimExample';

async function animate(scene: any) {
  const { Text, ThreeDAxes } = await import('manim-web');

  const axes = new ThreeDAxes({
    xRange: [-6, 6, 1],
    yRange: [-5, 5, 1],
    zRange: [-4, 4, 1],
    axisColor: '#ffffff',
    tipLength: 0.3,
    tipRadius: 0.12,
    shaftRadius: 0.008,
  });

  // Create a label that sits in 3D space but always faces the camera
  const label = new Text({ text: 'Origin', fontSize: 24 });
  label.moveTo([0, 0.5, 0]);

  const xLabel = new Text({ text: 'X', fontSize: 24 });
  xLabel.moveTo([6.5, 0, 0]);

  scene.add(axes, label, xLabel);

  // Make the labels always face the camera regardless of orbit angle
  scene.addFixedOrientationMobjects(label, xLabel);

  // Rotate the camera so the billboard effect is visible
  scene.beginAmbientCameraRotation(0.3);
  await scene.wait(999999);
}

function createScene(container: HTMLElement, manim: any) {
  return new manim.ThreeDScene(container, {
    width: 800,
    height: 450,
    backgroundColor: '#000000',
    phi: 75 * (Math.PI / 180),
    theta: -45 * (Math.PI / 180),
    distance: 20,
    fov: 30,
  });
}

export default function FixedOrientationMobjectsExample() {
  return <ManimExample animationFn={animate} createScene={createScene} />;
}
