// Auto-generated by generate-example-docs.mjs - do not edit
import React from 'react';
import ManimExample from '../ManimExample';

async function animate(scene: any) {
  const { Text, ThreeDAxes, UL } = await import('manim-web');

  const axes = new ThreeDAxes({
    xRange: [-6, 6, 1],
    yRange: [-5, 5, 1],
    zRange: [-4, 4, 1],
    xLength: 12,
    yLength: 10,
    zLength: 6,
    axisColor: '#ffffff',
    tipLength: 0.3,
    tipRadius: 0.12,
    shaftRadius: 0.008,
  });
  const text3d = new Text({ text: 'This is a 3D text' });
  scene.addFixedInFrameMobjects(text3d);
  text3d.toCorner(UL);
  scene.add(axes);
  await scene.wait();
}

function createScene(container: HTMLElement, manim: any) {
  return new manim.ThreeDScene(container, {
    width: 800,
    height: 450,
    backgroundColor: '#000000',
    phi: 75 * (Math.PI / 180),
    theta: -45 * (Math.PI / 180),
    distance: 20,
    fov: 30,
  });
}

export default function FixedInFrameMobjectTestExample() {
  return <ManimExample animationFn={animate} createScene={createScene} />;
}
