// Auto-generated by generate-example-docs.mjs - do not edit
import React from 'react';
import ManimExample from '../ManimExample';

async function animate(scene: any) {
  const { Axes, BLUE, BLUE_C, GRAY, GREEN_B, Scene, YELLOW, BLACK } = await import('manim-web');

  const ax = new Axes({
    xRange: [0, 5],
    yRange: [0, 6],
    xAxisConfig: { numbersToInclude: [2, 3] },
    tips: false,
  });
  const labels = ax.getAxisLabels();

  const curve1 = ax.plot((x) => 4 * x - Math.pow(x, 2), { xRange: [0, 4], color: BLUE_C });
  const curve2 = ax.plot((x) => 0.8 * Math.pow(x, 2) - 3 * x + 4, {
    xRange: [0, 4],
    color: GREEN_B,
  });

  const line1 = ax.getVerticalLine(ax.inputToGraphPoint(2, curve1), { color: YELLOW });
  const line2 = ax.getVerticalLine(ax.i2gp(3, curve1), { color: YELLOW });

  const riemannArea = ax.getRiemannRectangles(curve1, {
    xRange: [0.3, 0.6],
    dx: 0.03,
    color: BLUE,
    fillOpacity: 0.5,
  });
  const area = ax.getArea(curve2, [2, 3], { boundedGraph: curve1, color: GRAY, opacity: 0.5 });

  scene.add(ax, labels, curve1, curve2, line1, line2, riemannArea, area);
}

export default function GraphAreaPlotExample() {
  return <ManimExample animationFn={animate} />;
}
