// Auto-generated by generate-example-docs.mjs - do not edit
import React from 'react';
import ManimExample from '../ManimExample';

async function animate(scene: any) {
  const {
    BackgroundRectangle,
    Create,
    Dot,
    DOWN,
    FadeIn,
    FadeOut,
    ImageMobject,
    MED_SMALL_BUFF,
    PURPLE,
    RED,
    Scale,
    ScaleInPlace,
    Shift,
    smooth,
    Uncreate,
    UL,
    UP,
    UpdateFromFunc,
    scaleVec,
    Text,
  } = await import('manim-web');

  const image = new ImageMobject({
    pixelData: [
      [0, 100, 30, 200],
      [255, 0, 5, 33],
    ],
    height: 7,
  });
  const dot = new Dot().shift(scaleVec(2, UL));
  const frameText = new Text({ text: 'Frame', color: PURPLE, fontSize: 67 });
  const zoomedCameraText = new Text({ text: 'Zoomed camera', color: RED, fontSize: 67 });

  scene.add(image, dot);

  const zoomedCamera = scene.zoomedCamera;
  const zoomedDisplay = scene.zoomedDisplay;
  const frame = zoomedCamera.frame;
  const zoomedDisplayFrame = zoomedDisplay.displayFrame;

  frame.moveTo(dot);
  frame.setColor(PURPLE);
  zoomedDisplayFrame.setColor(RED);
  zoomedDisplay.shift(DOWN);

  const zdRect = new BackgroundRectangle(zoomedDisplay, {
    fillOpacity: 0,
    buff: MED_SMALL_BUFF,
  });
  scene.addForegroundMobject(zdRect);

  const unfoldCamera = new UpdateFromFunc(zdRect, (rect: any) => {
    rect.replace(zoomedDisplay);
  });

  frameText.nextTo(frame, DOWN);

  // Step 1: Create + FadeIn
  await scene.play(new Create(frame), new FadeIn(frameText, { shift: UP }));
  scene.activateZooming();

  // Step 2: PopOut + unfoldCamera
  await scene.play(scene.getZoomedDisplayPopOutAnimation(), unfoldCamera);

  zoomedCameraText.nextTo(zoomedDisplay, DOWN);
  // Step 3: FadeIn zoomedCameraText
  await scene.play(new FadeIn(zoomedCameraText, { shift: UP }));

  // Step 4: Scale + FadeOut
  await scene.play(
    new Scale(frame, { scaleFactor: [0.5, 1.5, 0] }),
    new Scale(zoomedDisplay, { scaleFactor: [0.5, 1.5, 0] }),
    new FadeOut(zoomedCameraText),
    new FadeOut(frameText),
  );
  await scene.wait();

  // Step 5: ScaleInPlace
  await scene.play(new ScaleInPlace(zoomedDisplay, { scaleFactor: 2 }));
  await scene.wait();

  // Step 6: Shift
  await scene.play(new Shift(frame, { direction: scaleVec(2.5, DOWN) }));
  await scene.wait();

  // Step 7: Reverse PopOut
  await scene.play(
    scene.getZoomedDisplayPopOutAnimation({ rateFunc: (t: number) => smooth(1 - t) }),
    unfoldCamera,
  );

  // Step 8: Uncreate + FadeOut
  await scene.play(new Uncreate(zoomedDisplayFrame), new FadeOut(frame));
  await scene.wait();
}

function createScene(container: HTMLElement, manim: any, dims: { width: number; height: number }) {
  return new manim.ZoomedScene(container, {
    width: dims.width,
    height: dims.height,
    backgroundColor: manim.BLACK,
    zoomFactor: 0.3,
    displayWidth: 6,
    displayHeight: 1,
    cameraFrameStrokeWidth: 3,
    displayFrameStrokeWidth: 3,
    displayFrameColor: manim.RED,
    renderTargetSize: 256,
  });
}

export default function MovingZoomedSceneAroundExample() {
  return <ManimExample animationFn={animate} createScene={createScene} />;
}
