// Auto-generated by generate-example-docs.mjs - do not edit
import React from 'react';
import ManimExample from '../ManimExample';

async function animate(scene: any) {
  const { Scene, VMobject, Dot, Rotating, Shift, UP, LEFT, RIGHT, BLACK } =
    await import('manim-web');

  const path = new VMobject();
  path.fillOpacity = 0;
  const dot = new Dot();
  path.setPointsAsCorners([dot.getCenter(), dot.getCenter()]);

  const updatePath = (pathMob) => {
    const previousPath = pathMob.copy();
    previousPath.addPointsAsCorners([dot.getCenter()]);
    pathMob.become(previousPath);
  };
  path.addUpdater(updatePath);

  scene.add(path, dot);

  await scene.play(new Rotating(dot, { angle: Math.PI, aboutPoint: RIGHT, duration: 2 }));
  await scene.wait();
  await scene.play(new Shift(dot, { direction: UP }));
  await scene.play(new Shift(dot, { direction: LEFT }));
  await scene.wait();
}

export default function PointWithTraceExample() {
  return <ManimExample animationFn={animate} />;
}
