// Auto-generated by generate-example-docs.mjs - do not edit
import React from 'react';
import ManimExample from '../ManimExample';

async function animate(scene: any) {
  const {
    Scene,
    Dot,
    Text,
    Line,
    Shift,
    AnimationGroup,
    RIGHT,
    BLACK,
    BLUE,
    RED,
    GREEN,
    YELLOW,
    PURPLE,
    ORANGE,
    WHITE,
    smooth,
    runningStart,
    thereAndBackWithPause,
    lingering,
    exponentialDecay,
    slowInto,
    scaleVec,
  } = await import('manim-web');

  // Rate functions to compare, each with a label and color
  const rateFunctions = [
    { name: 'smooth', rateFunc: smooth, color: BLUE },
    { name: 'runningStart', rateFunc: runningStart(-0.2), color: RED },
    { name: 'thereAndBackWithPause', rateFunc: thereAndBackWithPause(), color: GREEN },
    { name: 'lingering', rateFunc: lingering, color: YELLOW },
    { name: 'exponentialDecay', rateFunc: exponentialDecay(), color: PURPLE },
    { name: 'slowInto', rateFunc: slowInto, color: ORANGE },
  ];

  const ROW_COUNT = rateFunctions.length;
  const TOP_Y = 2.0;
  const ROW_SPACING = 0.7;
  const START_X = -2.5;
  const SHIFT_DISTANCE = 5.0;

  const dots = [];
  const shiftDirection = scaleVec(SHIFT_DISTANCE, RIGHT) as [number, number, number];

  for (let i = 0; i < ROW_COUNT; i++) {
    const y = TOP_Y - i * ROW_SPACING;
    const { name, color } = rateFunctions[i];

    // Label on the left
    const label = new Text({
      text: name,
      fontSize: 20,
      color: WHITE,
    });
    label.moveTo([START_X - 2.0, y, 0]);

    // Track line (faint guide)
    const trackLine = new Line({
      start: [START_X, y, 0],
      end: [START_X + SHIFT_DISTANCE, y, 0],
      color: '#333333',
      strokeWidth: 1,
    });

    // Dot at the start position
    const dot = new Dot({
      point: [START_X, y, 0],
      radius: 0.1,
      color,
    });

    scene.add(label, trackLine, dot);
    dots.push(dot);
  }

  // Build simultaneous shift animations with different rate functions
  const animations = dots.map(
    (dot, i) =>
      new Shift(dot, {
        direction: shiftDirection,
        duration: 3,
        rateFunc: rateFunctions[i].rateFunc,
      }),
  );

  await scene.play(new AnimationGroup(animations));
}

export default function RateFunctionsComparisonExample() {
  return <ManimExample animationFn={animate} />;
}
