// Auto-generated by generate-example-docs.mjs - do not edit
import React from 'react';
import ManimExample from '../ManimExample';

async function animate(scene: any) {
  const { Circle, ThreeDAxes } = await import('manim-web');

  const axes = new ThreeDAxes({
    xRange: [-6, 6, 1],
    yRange: [-5, 5, 1],
    zRange: [-4, 4, 1],
    axisColor: '#ffffff',
    tipLength: 0.3,
    tipRadius: 0.12,
    shaftRadius: 0.008,
  });

  const circle = new Circle({ radius: 1, color: '#FC6255' });
  // Circle points are in Manim x-y plane but VMobject renders them
  // directly in THREE.js coords. Rotate -90° around X to lay flat
  // on the ground plane (THREE.js x-z = Manim x-y).
  circle.rotation.x = -Math.PI / 2;

  scene.add(circle, axes);

  // Begin 3D illusion camera rotation (theta rotates at 2 rad/s,
  // phi oscillates sinusoidally for a wobbling 3D effect)
  scene.begin3DIllusionCameraRotation(2);
  await scene.wait(Math.PI / 2);

  // Stop illusion rotation
  scene.stop3DIllusionCameraRotation();

  // Reset camera orientation for replay
  scene.setCameraOrientation(75 * (Math.PI / 180), 30 * (Math.PI / 180));
}

function createScene(container: HTMLElement, manim: any, dims: { width: number; height: number }) {
  return new manim.ThreeDScene(container, {
    ...dims,
    backgroundColor: '#000000',
    phi: 75 * (Math.PI / 180),
    theta: 30 * (Math.PI / 180),
    distance: 20,
    fov: 30,
  });
}

export default function ThreeDCameraIllusionRotationExample() {
  return <ManimExample animationFn={animate} createScene={createScene} />;
}
