// Auto-generated by generate-example-docs.mjs - do not edit
import React from 'react';
import ManimExample from '../ManimExample';

async function animate(scene: any) {
  const { Angle, Line3D, ThreeDAxes, ValueTracker, WHITE, YELLOW, GREEN } =
    await import('manim-web');

  // Demo for issue #262: a 3D Angle whose arc grows continuously past π to 2π
  // when the rotation plane is pinned via the new `axis` option. Sweeps a
  // projection line around the +Y axis in the XZ plane so the arc should
  // stay coplanar with the two segments at every frame.

  const axes = new ThreeDAxes({
    xRange: [-3, 3, 1],
    yRange: [-3, 3, 1],
    zRange: [-3, 3, 1],
    axisColor: '#ffffff',
    tipLength: 0.25,
    tipRadius: 0.1,
    shaftRadius: 0.008,
  });

  const origin: [number, number, number] = [0, 0, 0];
  const radius = 2;
  const axisVec: [number, number, number] = [0, 1, 0];

  const refLine = new Line3D({ start: origin, end: [radius, 0, 0], color: YELLOW });

  const theta = new ValueTracker(0);

  const sweepEnd = (): [number, number, number] => [
    radius * Math.cos(theta.getValue()),
    0,
    -radius * Math.sin(theta.getValue()),
  ];

  const sweepLine = new Line3D({ start: origin, end: sweepEnd(), color: GREEN });
  sweepLine.addUpdater((mob) => {
    (mob as Line3D).setEnd(sweepEnd());
  });

  const angle = new Angle(
    { points: [[radius, 0, 0], origin, sweepEnd()] },
    { radius: 0.9, color: WHITE, axis: axisVec },
  );
  angle.addUpdater((mob) => {
    mob.become(
      new Angle(
        { points: [[radius, 0, 0], origin, sweepEnd()] },
        { radius: 0.9, color: WHITE, axis: axisVec },
      ),
    );
  });

  scene.add(axes, refLine, sweepLine, angle);

  // Sweep through the full 2π. Before the fix, the arc mirrors across the
  // reference line past π. With `axis` pinned, it keeps growing.
  await scene.play(theta.animateTo(2 * Math.PI, { duration: 6 }));
  await scene.wait(0.5);

  scene.setCameraOrientation(70 * (Math.PI / 180), -40 * (Math.PI / 180));

  if (new URLSearchParams(window.location.search).has('embed')) {
    document
      .querySelectorAll('.controls, .buttons, h1, #status')
      .forEach((el) => ((el as HTMLElement).style.display = 'none'));
    document.documentElement.style.cssText =
      'margin:0;padding:0;width:100%;height:100%;overflow:hidden;background:#000';
    document.body.style.cssText =
      'margin:0;padding:0;width:100%;height:100%;overflow:hidden;background:#000;display:flex;justify-content:center;align-items:center';
    const cont = document.getElementById('container');
    if (cont) {
      cont.style.cssText =
        'border:none;border-radius:0;width:100vw;height:100vh;display:flex;justify-content:center;align-items:center';
    }
    const playBtn = document.getElementById('playBtn') as HTMLButtonElement;
    if (playBtn) {
      setTimeout(() => playBtn.click(), 500);
      new MutationObserver(() => {
        if (!playBtn.disabled) setTimeout(() => playBtn.click(), 2000);
      }).observe(playBtn, { attributes: true, attributeFilter: ['disabled'] });
    }
  }
}

function createScene(container: HTMLElement, manim: any) {
  return new manim.ThreeDScene(container, {
    width: 800,
    height: 450,
    backgroundColor: '#000000',
    phi: 70 * (Math.PI / 180),
    theta: -40 * (Math.PI / 180),
    distance: 20,
    fov: 30,
    enableOrbitControls: true,
  });
}

export default function ThreeDReflexAngleExample() {
  return <ManimExample animationFn={animate} createScene={createScene} />;
}
