// Auto-generated by generate-example-docs.mjs - do not edit
import React from 'react';
import ManimExample from '../ManimExample';

async function animate(scene: any) {
  const { Scene, Text, Write, FadeIn, FadeOut, AnimationGroup, BLACK, WHITE, RED, DOWN, smooth } = await import('manim-js');

  const FONT_URL = './fonts/KaTeX_Main-Regular.ttf';
  const firstLine = new Text({
    text: 'Create cool animations',
    fontSize: 48,
    color: WHITE,
    fontUrl: FONT_URL,
  });
  const secondLine = new Text({
    text: 'using Manim',
    fontSize: 48,
    color: WHITE,
    fontUrl: FONT_URL,
  });
  const thirdLine = new Text({ text: 'Try it out yourself.', fontSize: 48, color: RED });

  await Promise.all([firstLine.loadGlyphs(), secondLine.loadGlyphs()]);
  secondLine.nextTo(firstLine, DOWN);

  await scene.wait(1);
  await scene.play(new Write(firstLine), new Write(secondLine));
  await scene.wait(1);

  // Cross-fade: fade out first line while fading in third line at same position
  scene.add(thirdLine);
  thirdLine.opacity = 0;
  await scene.play(
    new AnimationGroup([
      new FadeOut(firstLine, { duration: 1.5, rateFunc: smooth }),
      new FadeIn(thirdLine, { duration: 1.5, rateFunc: smooth }),
      new FadeOut(secondLine, { duration: 1.5, rateFunc: smooth }),
    ]),
  );
  await scene.wait(2);
}

export default function DisplayingTextExample() {
  return <ManimExample animationFn={animate} />;
}
