// Auto-generated by generate-example-docs.mjs - do not edit
import React from 'react';
import ManimExample from '../ManimExample';

async function animate(scene: any) {
  const { Scene, Text, MathTex, Write, ReplacementTransform, FadeOut, BLACK, WHITE, DOWN } = await import('manim-js');

  const FONT_URL = './fonts/KaTeX_Main-Regular.ttf';
  const firstLine = new Text({
    text: 'Manim also allows you',
    fontSize: 36,
    color: WHITE,
    fontUrl: FONT_URL,
  });
  const secondLine = new Text({
    text: 'to show beautiful math equations',
    fontSize: 36,
    color: WHITE,
    fontUrl: FONT_URL,
  });
  const equation = new MathTex({
    latex: 'd(p, q) = \\sqrt{\\sum_{i=1}^n (q_i - p_i)^2}',
    fontSize: 48,
    color: WHITE,
  });

  await Promise.all([firstLine.loadGlyphs(), secondLine.loadGlyphs()]);
  secondLine.nextTo(firstLine, DOWN);

  await equation.waitForRender();

  await scene.play(new Write(firstLine), new Write(secondLine));
  await scene.wait(1);
  await scene.play(new ReplacementTransform(firstLine, equation), new FadeOut(secondLine));
  await scene.wait(3);
}

export default function DisplayingEquationsExample() {
  return <ManimExample animationFn={animate} />;
}
