// Auto-generated by generate-example-docs.mjs - do not edit
import React from 'react';
import ManimExample from '../ManimExample';

async function animate(scene: any) {
  const { Text, ThreeDAxes, UL } = await import('manim-js');

  const axes = new ThreeDAxes({
    xRange: [-6, 6, 1],
    yRange: [-6, 6, 1],
    zRange: [-6, 6, 1],
    xLength: 10.5,
    yLength: 10.5,
    zLength: 10.5,
    axisColor: '#bababa',
    tipLength: 0.35,
    tipRadius: 0.15,
    shaftRadius: 0.03,
  });
  const text3d = new Text({ text: 'This is a 3D text' });
  scene.addFixedInFrameMobjects(text3d);
  text3d.toCorner(UL);
  scene.add(axes);
  await scene.wait();
}

function createScene(container: HTMLElement, manim: any) {
  return new manim.ThreeDScene(container, {
    width: 800,
    height: 450,
    backgroundColor: '#000000',
    phi: 75 * (Math.PI / 180),
    theta: -45 * (Math.PI / 180),
    distance: 15,
    fov: 23,
  });
}

export default function FixedInFrameMobjectTestExample() {
  return <ManimExample animationFn={animate} createScene={createScene} />;
}
