// Auto-generated by generate-example-docs.mjs - do not edit
import React from 'react';
import ManimExample from '../ManimExample';

async function animate(scene: any) {
  const { Scene, Square, Shift, MoveToTarget, Scale, Rotate, BLUE, ORANGE, LEFT, BLACK } =
    await import('manim-js');

  const square = new Square({ color: BLUE, fillOpacity: 1 });

  await scene.play(new Shift(square, { direction: LEFT }));

  square.generateTarget();
  square.targetCopy.setFill(ORANGE);
  await scene.play(new MoveToTarget(square));

  await scene.play(new Scale(square, { scaleFactor: 0.3 }));

  await scene.play(new Rotate(square, { angle: 0.4 }));
}

export default function MovingAroundExample() {
  return <ManimExample animationFn={animate} />;
}
