// Auto-generated by generate-example-docs.mjs - do not edit
import React from 'react';
import ManimExample from '../ManimExample';

async function animate(scene: any) {
  const { Scene, Square, MoveToTarget, BLUE, ORANGE, LEFT, BLACK } = await import('manim-js');

  const square = new Square({ color: BLUE, fillOpacity: 1 });

  scene.add(square);

  square.generateTarget();
  square.targetCopy.shift(LEFT);
  await scene.play(new MoveToTarget(square));

  square.generateTarget();
  square.targetCopy.setFill(ORANGE);
  await scene.play(new MoveToTarget(square));

  square.generateTarget();
  square.targetCopy.scale(0.3);
  await scene.play(new MoveToTarget(square));

  square.generateTarget();
  square.targetCopy.rotate(0.4);
  await scene.play(new MoveToTarget(square));
}

export default function MovingAroundExample() {
  return <ManimExample animationFn={animate} />;
}
