// Auto-generated by generate-example-docs.mjs - do not edit
import React from 'react';
import ManimExample from '../ManimExample';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
async function animate(scene: any) {
  const { VGroup, Dot, Shift, LEFT, ORIGIN, RIGHT, RED, YELLOW, scaleVec, subVec } =
    await import('manim-js');

  const group = new VGroup(
    new Dot({ point: LEFT }),
    new Dot({ point: ORIGIN }),
    new Dot({ point: RIGHT, color: RED }),
    new Dot({ point: scaleVec(2, RIGHT) }),
  ).scale(1.4);

  const dest = new Dot({ point: [4, 3, 0], color: YELLOW });

  scene.add(group, dest);

  await scene.play(
    new Shift(group, {
      direction: subVec(dest.getCenter(), group.get(2).getCenter()),
    }),
  );
  await scene.wait(0.5);
}

export default function MovingGroupToDestinationExample() {
  return <ManimExample animationFn={animate} />;
}
