// Auto-generated by generate-example-docs.mjs - do not edit
import React from 'react';
import ManimExample from '../ManimExample';

async function animate(scene: any) {
  const { Angle, FadeToColor, LEFT, Line, MathTex, RED, RIGHT, SMALL_BUFF, Scene, ValueTracker, BLACK, WHITE } = await import('manim-js');

  const rotation_center = LEFT;

  const theta_tracker = new ValueTracker(110);
  const line1 = new Line({ start: LEFT, end: RIGHT });
  const line_moving = new Line({ start: LEFT, end: RIGHT });
  const line_ref = line_moving.copy();
  line_moving.rotate(theta_tracker.getValue() * (Math.PI / 180), { aboutPoint: rotation_center });
  const a = new Angle({ line1: line1, line2: line_moving }, { radius: 0.5, otherAngle: false });
  const tex = new MathTex({ latex: '\\theta', color: WHITE });
  await tex.waitForRender();
  tex.moveTo(
    new Angle(
      { line1: line1, line2: line_moving },
      { radius: 0.5 + 3 * SMALL_BUFF, otherAngle: false },
    ).pointFromProportion(0.5),
  );

  scene.add(line1, line_moving, a, tex);
  await scene.wait(1);

  line_moving.addUpdater((x) => {
    x.become(line_ref.copy());
    x.rotate(theta_tracker.getValue() * (Math.PI / 180), { aboutPoint: rotation_center });
  });

  a.addUpdater((x) =>
    x.become(new Angle({ line1: line1, line2: line_moving }, { radius: 0.5, otherAngle: false })),
  );
  tex.addUpdater((x) =>
    x.moveTo(
      new Angle(
        { line1: line1, line2: line_moving },
        { radius: 0.5 + 3 * SMALL_BUFF, otherAngle: false },
      ).pointFromProportion(0.5),
    ),
  );

  await scene.play(theta_tracker.animateTo(40));
  await scene.play(theta_tracker.animateTo(theta_tracker.getValue() + 140));
  await scene.play(new FadeToColor(tex, { color: RED, duration: 0.5 }));
  await scene.play(theta_tracker.animateTo(350));

  await scene.wait(1);
}

export default function MovingAngleExample() {
  return <ManimExample animationFn={animate} />;
}
