// Auto-generated by generate-example-docs.mjs - do not edit
import React from 'react';
import ManimExample from '../ManimExample';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
async function animate(scene: any) {
  const { Dot, VGroup, Line, ValueTracker, BLUE, GREEN, RED, RIGHT } = await import('manim-js');

  const d1 = new Dot({ color: BLUE });
  const d2 = new Dot({ color: GREEN });
  new VGroup(d1, d2).arrange(RIGHT, 1);
  const l1 = new Line({ start: d1.getCenter(), end: d2.getCenter() }).setColor(RED);
  const x = new ValueTracker(0);
  const y = new ValueTracker(0);
  d1.addUpdater((z) => z.setX(x.getValue()));
  d2.addUpdater((z) => z.setY(y.getValue()));
  l1.addUpdater((z) => z.become(new Line({ start: d1.getCenter(), end: d2.getCenter() })));
  scene.add(d1, d2, l1);
  await scene.play(x.animateTo(5));
  await scene.play(y.animateTo(4));
  await scene.wait();
}

export default function MovingDotsExample() {
  return <ManimExample animationFn={animate} />;
}
