// Auto-generated by generate-example-docs.mjs - do not edit
import React from 'react';
import ManimExample from '../ManimExample';

function createZoomedScene(container: HTMLElement, manim: any) {
  return new manim.ZoomedScene(container, {
    width: 800,
    height: 450,
    backgroundColor: '#000000',
    cameraFrameWidth: 3,
    cameraFrameHeight: 3,
    zoomFactor: 0.3,
    displayWidth: 6,
    displayHeight: 1,
    cameraFrameStrokeWidth: 3,
    displayFrameStrokeWidth: 20,
    displayFrameColor: manim.RED,
  });
}

async function animate(scene: any) {
  const {
    BackgroundRectangle,
    Create,
    Dot,
    DOWN,
    FadeIn,
    FadeOut,
    MED_SMALL_BUFF,
    PURPLE,
    RED,
    Scale,
    ScaleInPlace,
    Shift,
    Text,
    UL,
    Uncreate,
    UP,
    UpdateFromFunc,
    VGroup,
    scaleVec,
  } = await import('manim-js');

  // Create a grid of colored dots as content
  const dots: any[] = [];
  for (let row = 0; row < 15; row++) {
    for (let col = 0; col < 15; col++) {
      const r = Math.floor((row / 14) * 255);
      const g = Math.floor((col / 14) * 255);
      const b = Math.floor(((row + col) / 28) * 255);
      const color = `rgb(${r}, ${g}, ${b})`;
      const dot = new Dot({ radius: 0.15, color });
      dot.moveTo([col * 0.45 - 3.15, row * 0.45 - 3.15, 0]);
      dots.push(dot);
    }
  }
  const image = new VGroup(...dots);
  image.moveTo([0, 0, 0]);

  const dot = new Dot().shift(scaleVec(2, UL));
  const frameText = new Text({ text: 'Frame', color: PURPLE, fontSize: 48 });
  const zoomedCameraText = new Text({ text: 'Zoomed camera', color: RED, fontSize: 48 });

  scene.add(image, dot);

  const frame = scene.zoomedCamera.frame;
  const zoomedDisplay = scene.zoomedDisplay;
  const zoomedDisplayFrame = zoomedDisplay.displayFrame;

  frame.moveTo(dot);
  frame.setColor(PURPLE);
  zoomedDisplayFrame.setColor(RED);
  zoomedDisplay.shift([0, -2, 0]);

  const zdRect = new BackgroundRectangle(zoomedDisplay, {
    fillOpacity: 0,
    buff: MED_SMALL_BUFF,
  });
  scene.addForegroundMobject(zdRect);

  const unfoldCamera = new UpdateFromFunc(zdRect, (rect: any) => {
    rect.replace(zoomedDisplay);
  });

  frameText.nextTo(frame, DOWN);

  await scene.play(new Create(frame), new FadeIn(frameText, { shift: UP }));
  scene.activateZooming();

  const popOut = scene.getZoomedDisplayPopOutAnimation();
  zoomedDisplay.moveTo(popOut.startPosition);
  await scene.play(
    new Shift(zoomedDisplay, {
      direction: [
        popOut.endPosition[0] - popOut.startPosition[0],
        popOut.endPosition[1] - popOut.startPosition[1],
        popOut.endPosition[2] - popOut.startPosition[2],
      ],
    }),
    unfoldCamera,
  );

  zoomedCameraText.nextTo(zoomedDisplayFrame, DOWN);
  await scene.play(new FadeIn(zoomedCameraText, { shift: UP }));

  await scene.play(
    new Scale(frame, { scaleFactor: [0.5, 1.5, 1] }),
    new Scale(zoomedDisplay, { scaleFactor: [0.5, 1.5, 1] }),
    new FadeOut(zoomedCameraText),
    new FadeOut(frameText),
  );
  await scene.wait();

  await scene.play(new ScaleInPlace(zoomedDisplay, { scaleFactor: 2 }));
  await scene.wait();

  await scene.play(new Shift(frame, { direction: scaleVec(2.5, DOWN) }));
  await scene.wait();
}

export default function MovingZoomedSceneAroundExample() {
  return <ManimExample animationFn={animate} createScene={createZoomedScene} />;
}
