// Auto-generated by generate-example-docs.mjs - do not edit
import React from 'react';
import ManimExample from '../ManimExample';

async function animate(scene: any) {
  const { Create, MathTex, ReplacementTransform, Scene, SurroundingRectangle, Write } = await import('manim-web');

  const text = new MathTex({
    latex: ['\\frac{d}{dx}f(x)g(x)=', 'f(x)\\frac{d}{dx}g(x)', '+', 'g(x)\\frac{d}{dx}f(x)'],
  });
  await text.waitForRender();
  await scene.play(new Write(text));
  const framebox1 = new SurroundingRectangle(text.getPart(1), { buff: 0.1 });
  const framebox2 = new SurroundingRectangle(text.getPart(3), { buff: 0.1 });
  await scene.play(new Create(framebox1));
  await scene.wait();
  await scene.play(new ReplacementTransform(framebox1, framebox2));
  await scene.wait();
}

export default function MovingFrameBoxExample() {
  return <ManimExample animationFn={animate} />;
}
