// Auto-generated by generate-example-docs.mjs - do not edit
import React from 'react';
import ManimExample from '../ManimExample';

async function animate(scene: any) {
  const {
    Scene,
    Create,
    FadeIn,
    FadeOut,
    Transform,
    ApplyPointwiseFunction,
    Text,
    MathTex,
    NumberPlane,
    VGroup,
    UP,
    DOWN,
    UL,
    BLACK,
    WHITE,
  } = await import('manim-js');

  const FONT_URL = 'https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/fonts/KaTeX_Main-Regular.ttf';

  // Part 1: Title and equation (Write title, FadeIn equation from below)
  const title = new Text({
    text: 'This is some LaTeX',
    fontSize: 48,
    color: WHITE,
    fontUrl: FONT_URL,
  });
  const basel = new MathTex({ latex: '\\sum_{n=1}^\\infty \\frac{1}{n^2} = \\frac{\\pi^2}{6}' });
  await basel.waitForRender?.();

  new VGroup(title, basel).arrange(DOWN);
  scene.add(title, basel);
  await scene.play(new FadeIn(title), new FadeIn(basel, { shift: DOWN }));
  await scene.wait(1);

  // Part 2: Transform title to UL corner, fade out equation downward
  const transformTitle = new Text({
    text: 'That was a transform',
    fontSize: 48,
    color: WHITE,
    fontUrl: FONT_URL,
  });
  await transformTitle.loadGlyphs();
  transformTitle.toCorner(UL);
  await scene.play(new Transform(title, transformTitle), new FadeOut(basel, { shift: DOWN }));
  await scene.wait(1);

  // Part 3: Number plane grid with title
  const grid = new NumberPlane();
  const gridTitle = new Text({
    text: 'This is a grid',
    fontSize: 72,
    color: WHITE,
    fontUrl: FONT_URL,
  });
  await gridTitle.loadGlyphs();
  gridTitle.moveTo(transformTitle);

  await scene.play(
    new FadeOut(title),
    new FadeIn(gridTitle, { shift: UP }),
    new Create(grid, { duration: 3, lagRatio: 0.1 }),
  );
  await scene.wait(1);

  // Part 4: Non-linear grid transform (sin warp)
  const gridTransformTitle = new Text({
    text: 'That was a non-linear function\napplied to the grid',
    fontSize: 48,
    color: WHITE,
    fontUrl: FONT_URL,
  });
  await gridTransformTitle.loadGlyphs();
  gridTransformTitle.moveTo(gridTitle, UL);
  grid.prepareForNonlinearTransform();
  await scene.play(
    new ApplyPointwiseFunction(
      grid,
      (p) => {
        return [p[0] + Math.sin(p[1]), p[1] + Math.sin(p[0]), p[2]];
      },
      { duration: 3 },
    ),
  );
  await scene.wait(1);

  // Part 5: Transform grid title to explain what happened
  await scene.play(new Transform(gridTitle, gridTransformTitle));
  await scene.wait(1);
}

export default function OpeningManimExample() {
  return <ManimExample animationFn={animate} />;
}
