// Auto-generated by generate-example-docs.mjs - do not edit
import React from 'react';
import ManimExample from '../ManimExample';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
async function animate(scene: any) {
  const {
    BLUE,
    Circle,
    Dot,
    GrowFromCenter,
    Line,
    MoveAlongPath,
    RIGHT,
    Rotating,
    Transform,
    linear,
  } = await import('manim-js');

  const circle = new Circle({ radius: 1, color: BLUE });
  const dot = new Dot();
  const dot2 = dot.copy().shift(RIGHT);
  scene.add(dot);

  const line = new Line({ start: [3, 0, 0], end: [5, 0, 0] });
  scene.add(line);

  await scene.play(new GrowFromCenter(circle));
  await scene.play(new Transform(dot, dot2));
  await scene.play(new MoveAlongPath(dot, { path: circle, duration: 2, rateFunc: linear }));
  await scene.play(new Rotating(dot, { aboutPoint: [2, 0, 0], duration: 1.5 }));
  await scene.wait();
}

export default function PointMovingOnShapesExample() {
  return <ManimExample animationFn={animate} />;
}
