// Auto-generated by generate-example-docs.mjs - do not edit
import React from 'react';
import ManimExample from '../ManimExample';

async function animate(scene: any) {
  const { Axes, BLUE, GREEN, Line, RED, Scene, UP, UR, VGroup, WHITE, YELLOW, scaleVec, BLACK } = await import('manim-js');

  const axes = new Axes({
    xRange: [-10, 10.3, 1],
    yRange: [-1.5, 1.5, 1],
    xLength: 10,
    axisConfig: { color: GREEN },
    xAxisConfig: {
      numbersToInclude: [-10, -8, -6, -4, -2, 0, 2, 4, 6, 8, 10],
      numbersWithElongatedTicks: [-10, -8, -6, -4, -2, 0, 2, 4, 6, 8, 10],
    },
    tips: false,
  });
  const axesLabels = axes.getAxisLabels();
  const sinGraph = axes.plot((x) => Math.sin(x), { color: BLUE });
  const cosGraph = axes.plot((x) => Math.cos(x), { color: RED });

  const sinLabel = axes.getGraphLabel(sinGraph, '\\sin(x)', {
    xVal: -10,
    direction: scaleVec(0.5, UP),
  });
  const cosLabel = axes.getGraphLabel(cosGraph, { label: '\\cos(x)' });

  const vertLine = axes.getVerticalLine(axes.i2gp(2 * Math.PI, cosGraph), {
    color: YELLOW,
    lineFunc: Line,
  });
  const lineLabel = axes.getGraphLabel(cosGraph, 'x=2\\pi', {
    xVal: 2 * Math.PI,
    direction: UR,
    color: WHITE,
  });

  const plot = new VGroup(axes, sinGraph, cosGraph, vertLine);
  const labels = new VGroup(axesLabels, sinLabel, cosLabel, lineLabel);
  scene.add(plot, labels);
}

export default function SinCosPlotExample() {
  return <ManimExample animationFn={animate} />;
}
