// Auto-generated by generate-example-docs.mjs - do not edit
import React from 'react';
import ManimExample from '../ManimExample';

async function animate(scene: any) {
  const { Scene, Text, Write, BLACK, WHITE } = await import('manim-js');

  const FONT_URL = './fonts/KaTeX_Main-Regular.ttf';

  const text = new Text({
    text: 'This is some LaTeX',
    fontSize: 48,
    color: WHITE,
    fontUrl: FONT_URL,
  });
  await text.loadGlyphs();
  scene.add(text);
  await scene.play(new Write(text, { duration: 5 }));
}

export default function TestWriteExample() {
  return <ManimExample animationFn={animate} />;
}
