// Auto-generated by generate-example-docs.mjs - do not edit
import React from 'react';
import ManimExample from '../ManimExample';

async function animate(scene: any) {
  const { ThreeDAxes, Surface3D, RED_D, RED_E } = await import('manim-js');

  const axes = new ThreeDAxes({
    xRange: [-5, 5, 1],
    yRange: [-5, 5, 1],
    zRange: [-5, 5, 1],
    xLength: 10,
    yLength: 10,
    zLength: 10,
    axisColor: '#ffffff',
    tipLength: 0.2,
    tipRadius: 0.08,
    shaftRadius: 0.01,
  });

  // Parametric sphere: radius 1.5
  // Python Manim convention: u = latitude [-PI/2, PI/2], v = longitude [0, TAU]
  // Manim coords: (x, y, z) where z is up
  // manim-js Surface3D renders in THREE.js space directly
  // THREE.js mapping from Manim: (mx, mz, -my)
  const sphere = new Surface3D({
    func: (u, v) => {
      // Manim coordinates
      const mx = 1.5 * Math.cos(u) * Math.cos(v);
      const my = 1.5 * Math.cos(u) * Math.sin(v);
      const mz = 1.5 * Math.sin(u);
      // Convert to THREE.js: (mx, mz, -my)
      return [mx, mz, -my];
    },
    uRange: [-Math.PI / 2, Math.PI / 2],
    vRange: [0, Math.PI * 2],
    uResolution: 15,
    vResolution: 32,
    checkerboardColors: [RED_D, RED_E],
  });

  // Python Manim: self.renderer.camera.light_source.move_to(3*IN)
  // IN = [0, 0, -1] in Manim 3D (Z-up), so 3*IN = [0, 0, -3]
  // THREE.js mapping: (mx, mz, -my) = (0, -3, 0)
  // Reduce roughness for brighter appearance matching Python Manim
  const threeObj = sphere.getThreeObject();
  threeObj.traverse((child: THREE.Object3D) => {
    if (child instanceof THREE.Mesh) {
      const mat = child.material as THREE.MeshStandardMaterial;
      mat.roughness = 0.6;
    }
  });

  // Python Manim: self.renderer.camera.light_source.move_to(3*IN)
  // IN = [0, 0, -1] in Manim 3D (Z-up), so 3*IN = [0, 0, -3]
  // THREE.js mapping: (mx, mz, -my) = (0, -3, 0)
  scene.lighting.removeAll();
  scene.lighting.addAmbient({ intensity: 1.0 });
  scene.lighting.addDirectional({ position: [0, 5, 3], intensity: 2.5 });
  scene.lighting.addDirectional({ position: [-3, -5, 0], intensity: 0.5 });

  scene.add(axes);
  scene.add(sphere);
  await scene.wait();
}

function createScene(container: HTMLElement, manim: any) {
  return new manim.ThreeDScene(container, {
    width: 800,
    height: 450,
    backgroundColor: '#000000',
    phi: 75 * (Math.PI / 180),
    theta: 30 * (Math.PI / 180),
    distance: 20,
    fov: 30,
  });
}

export default function ThreeDLightSourcePositionExample() {
  return <ManimExample animationFn={animate} createScene={createScene} />;
}
