// Auto-generated by generate-example-docs.mjs - do not edit
import React from 'react';
import ManimExample from '../ManimExample';

async function animate(scene: any) {
  const { Circle, ThreeDAxes } = await import('manim-js');

  const axes = new ThreeDAxes({
    xRange: [-6, 6, 1],
    yRange: [-5, 5, 1],
    zRange: [-4, 4, 1],
    xLength: 12,
    yLength: 10,
    zLength: 6,
    axisColor: '#ffffff',
    tipLength: 0.3,
    tipRadius: 0.12,
    shaftRadius: 0.008,
  });

  const circle = new Circle({ radius: 1, color: '#FC6255' });
  // Circle points are in Manim x-y plane but VMobject renders them
  // directly in THREE.js coords. Rotate -90° around X to lay flat
  // on the ground plane (THREE.js x-z = Manim x-y).
  circle.rotation.x = -Math.PI / 2;

  scene.add(circle, axes);

  // Begin ambient camera rotation (theta rotates at 0.1 rad/s)
  scene.beginAmbientCameraRotation(0.1);
  await scene.wait(3);

  // Stop rotation and animate camera back to original orientation
  scene.stopAmbientCameraRotation();
  await scene.moveCamera({
    phi: 75 * (Math.PI / 180),
    theta: 30 * (Math.PI / 180),
    duration: 1,
  });
  await scene.wait(1);

  // Reset camera orientation for replay
  scene.setCameraOrientation(75 * (Math.PI / 180), 30 * (Math.PI / 180));
}

function createScene(container: HTMLElement, manim: any) {
  return new manim.ThreeDScene(container, {
  width: 800,
  height: 450,
  backgroundColor: '#000000',
  phi: 75 * (Math.PI / 180),
  theta: 30 * (Math.PI / 180),
  distance: 20,
  fov: 30,
});
}

export default function ThreeDCameraRotationExample() {
  return <ManimExample animationFn={animate} createScene={createScene} />;
}
