// Auto-generated by generate-example-docs.mjs - do not edit
import React from 'react';
import ManimExample from '../ManimExample';

async function animate(scene: any) {
  const { ThreeDAxes, Surface3D, ORANGE, BLUE } = await import('manim-js');

  const sigma = 0.4;
  const mu = [0.0, 0.0];

  // Gaussian surface: parametric function mapping (u,v) to 3D point
  // Surface3D func returns [x, y, z] used directly as THREE.js coordinates.
  // Manim Z-up -> THREE.js Y-up: return [manimX, manimZ, -manimY]
  const gaussSurface = new Surface3D({
    func: (u: number, v: number) => {
      const x = u;
      const y = v;
      const dx = x - mu[0];
      const dy = y - mu[1];
      const d = Math.sqrt(dx * dx + dy * dy);
      const z = Math.exp(-(d * d) / (2.0 * sigma * sigma));
      // Manim coords (x, y, z) -> THREE.js coords (x, z, -y)
      return [x, z, -y];
    },
    uRange: [-2, 2],
    vRange: [-2, 2],
    uResolution: 24,
    vResolution: 24,
    checkerboardColors: [ORANGE, BLUE],
    opacity: 0.85,
  });

  // Scale by 2 about origin (matches Python: gauss_plane.scale(2, about_point=ORIGIN))
  gaussSurface.scale(2);

  const axes = new ThreeDAxes({
    xRange: [-6, 6, 1],
    yRange: [-5, 5, 1],
    zRange: [-4, 4, 1],
    xLength: 12,
    yLength: 10,
    zLength: 6,
    axisColor: '#ffffff',
    tipLength: 0.3,
    tipRadius: 0.12,
    shaftRadius: 0.008,
  });

  scene.add(axes);
  scene.add(gaussSurface);
  await scene.wait();
}

function createScene(container: HTMLElement, manim: any) {
  return new manim.ThreeDScene(container, {
    width: 800,
    height: 450,
    backgroundColor: '#000000',
    phi: 75 * (Math.PI / 180),
    theta: -30 * (Math.PI / 180),
    distance: 20,
    fov: 30,
  });
}

export default function ThreeDSurfacePlotExample() {
  return <ManimExample animationFn={animate} createScene={createScene} />;
}
