// Auto-generated by generate-example-docs.mjs - do not edit
import React from 'react';
import ManimExample from '../ManimExample';

async function animate(scene: any) {
  const { Arrow, DOWN, Dot, NumberPlane, ORIGIN, RIGHT, Scene, Text } = await import('manim-js');

  async function vectorArrow(scene: Scene) {
    const dot = new Dot({ point: ORIGIN });
    const arrow = new Arrow({ start: ORIGIN, end: [2, 2, 0] });
    const numberplane = new NumberPlane();
    const originText = new Text({ text: '(0, 0)' }).nextTo(dot, DOWN);
    const tipText = new Text({ text: '(2, 2)' }).nextTo(arrow.getEndPoint(), RIGHT);
    scene.add(numberplane, dot, arrow, originText, tipText);
  }

  await vectorArrow(scene);
}

export default function VectorArrowExample() {
  return <ManimExample animationFn={animate} />;
}
