import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: ['intro', 'getting-started', 'examples', { type: 'autogenerated', dirName: 'api' }],
};

export default sidebars;
